name: Проверка структуры проекта

on: [push, pull_request]

jobs:
  check-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Проверка index.html
        run: test -f index.html

      - name: Проверка папки styles и файлов
        run: |
          test -d styles
          test -f styles/style.css
          test -f styles/preloader.css
          test -f styles/error.css

      - name: Проверка папки scripts
        run: |
          test -d scripts
          test -f scripts/script.js

      - name: ✅ Всё в порядке!
        run: echo "Структура проекта корректна"
